### ISSUE TITLE
Add functionality to invalidate token 

### ISSUE THREAD

**Issue by dianacamacho** [LaunchPadLab/lp_token_auth#26]
Backend cannot currently control whether a user is logged in, must be managed on front-end

**Comment by rkillackey** [comment]
Closing for now, as there's not an easy way to do this with JWTs, which are meant to be stateless. More info here: https://stackoverflow.com/a/23089839 + http://waiting-for-dev.github.io/blog/2017/01/24/jwt_revocation_strategies/

We can reevaluate at a later point if it becomes necessary on a project.
